---
title: "About"
---

These lecture notes were prepared by Stefano Allesina (`sallesina@uchicago.edu`) for the graduate class *ECEV 42900, Theoretical Ecology*, taught at the University of Chicago in Winter Quarter 2024. The notes grew a set of notes from Sarah Cobey.

Call-out sections contain special material:

::: {.callout-note collapse="fales"}
## Mathematical review

This type of call-out contains brief reviews of important mathematical concepts.
:::

::: {.callout-tip collapse="false"}
## Computing in `R`

This type of call-out contains information about coding dynamical systems in `R`.
:::

::: {.callout-warning collapse="false"}
## Exercises

This type of call-out contains exercises that should be submitted by the following class.
:::

### Resources

These are good introductions to theoretical ecology:

- Case, [*An Illustrated Guide to Theoretical Ecology*](https://global.oup.com/ushe/product/an-illustrated-guide-to-theoretical-ecology-9780195085129?cc=us&lang=en&), 1999

- May and McLean, [*Theoretical Ecology: Principles and Applications*](https://academic.oup.com/book/42041), 2007

- Gotelli, [*A primer of ecology*](https://global.oup.com/academic/product/a-primer-of-ecology-9780878933181?cc=us&lang=en&), 2008

- Hofbauer and Sigmund [*Evolutionary Games and Population Dynamics*](https://www.cambridge.org/core/books/evolutionary-games-and-population-dynamics/A8D94EBE6A16837E7CB3CED24E1948F8), 1998

Books on disease dynamics:

- Anderson and May [*Infectious Diseases of Humans: Dynamics and Control*](https://global.oup.com/academic/product/infectious-diseases-of-humans-9780198540403?cc=us&lang=en&), 1992

- Keeling and Rohani [*Modelling Infectious Diseases*](https://press.princeton.edu/books/hardcover/9780691116174/modeling-infectious-diseases-in-humans-and-animals), 2008

### Course policies

The ethos of the course is collaborative rather than competitive. The instructors and TA are happy to help with assignments and clarifications. The first point of contact should be the TA, Kiseok Lee (`kiseoklee@uchicago.edu`); you can also email Stefano Allesina (`sallesina@uchicago.edu`) or Greg Dwyer (`gdwyer@uchicago.edu`) to set up a meeting. 

Students are expected to work in accordance with the University Policy of Academic Integrity, which can be found [here](https://college.uchicago.edu/student-services/academic-integrity-student-conduct).

Students can collaborate, but graded homework should be completed by each student independently, and not copied from others or from online resources. Students can use online resources (e.g., StackOverflow, ChatGPT, or other LLMs) to help with coding, but should explicitly acknowledge sources whenever this is the case. Students should make sure that the code is correct, rather than blindly trusting these services.

Grading: students should submit assigned homework by the beginning of the following class. Incomplete or late homework will be assigned zero points. The homework can be amended and resubmitted, as long as the original submission was complete, turned-in in time, and displayed solid effort. The grade is amended accordingly.

### Mathematical background

Following the material requires basic notions in calculus, linear algebra and dynamical systems. Students should be familiar with:

- Functions, exponential function, logarithm
- Limits
- Derivatives and chain rule
- Integration of functions in one and several variables

These concepts will be briefly reviewed in class; students who feel they will need to work on these at their own pace are encouraged to approach them before class:

- Taylor series
- Vectors, dot product, cross product
- Matrix product, transpose, determinant, eigenvalue decomposition
- Positive and negative definiteness of a matrix

These are good websites offering a brief review of these materials, and cheat sheets reporting the main formulas:

- [Paul's Online Notes](https://tutorial.math.lamar.edu/) covering calculus I, II and III as well as dynamical systems; the cheat sheets are excellent.

- The legendary Linear Algebra class by [Gilbert Strang](https://www.youtube.com/watch?v=7UJ4CFRGd-U&list=PLE7DDD91010BC51F8), who has written popular books on the subject, and taught legions of students at MIT.

- Ziko Kolter has published a brief [review of linear algebra](https://cs229.stanford.edu/section/cs229-linalg.pdf) concepts.

- Linear algebra [in four pages](https://minireference.com/static/tutorials/linear_algebra_in_4_pages.pdf) by  Ivan Savov.

- Linear algebra [visualized](https://www.3blue1brown.com/topics/linear-algebra) by 3Blue1Brown.

- Steve Brunton's (U. Washington) YouTube channel contains extremely well-done lectures on dynamical systems; for example, here are reviews of [derivatives](https://www.youtube.com/watch?v=-NhgElcA3K8), [Taylor series](https://www.youtube.com/watch?v=ebfOSDj4j3I), [simulating the logistic map](https://www.youtube.com/watch?v=_BvAkyuWhOI), [integrating ODEs in a computer](https://www.youtube.com/watch?v=W-wxKgjBDnc).
